---
- name: Install Navidrome
  become: true
  tags: install
  block:

    - name: Add media group
      ansible.builtin.group:
        name: media
        gid: "{{ media_gid }}"
        state: present

    - name: Add navidrome user
      ansible.builtin.user:
        name: navidrome
        uid: "{{ navidrome_uid }}"
        group: media

    - name: Create navidrome data directory
      ansible.builtin.file:
        path: /home/navidrome/data
        state: directory
        mode: "770"
        owner: navidrome
        group: media

    - name: Create navidrome_music volume
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr={{ nas }},nolock,soft,rw"
          device: "{{ navidrome_music_nfs }}"
        volume_name: navidrome_music

    - name: Create navidrome container
      community.docker.docker_container:
        name: navidrome
        image: deluan/navidrome:latest
        user: "{{ navidrome_uid }}:{{ media_gid }}"
        pull: true
        restart_policy: unless-stopped
        volumes:
          - "/home/navidrome/data:/data"
          - "navidrome_music:/music:ro"
        networks:
          - name: proxy_net
